### ISSUE TITLE
Include tests for pytest-vw in the PyPi distribution?

### ISSUE THREAD

**Issue by jgarte** [The-Compiler/pytest-vw#4]
## Problem

Hi Florian,

The PyPi distribution of `pytest-vw` does not include the tests.

## Solution

The PyPi distributed tarball includes the tests:

https://pypi.org/project/pytest-vw/#files

## Additional context / Questions

GNU/Linux Distribution packagers often run the tests when packaging software. If they get the sources from PyPi and the tests are not included with the sources then they have to resort to getting an unreleased commit hash or tag from GitHub, etc.

What do you think about the practice of including the tests in a PyPi release overall?

Should the Python community include tests in the PyPi distribution?

**Comment by The-Compiler** [comment]
In general, I suppose it's a good idea. I used to be against this for e.g. qutebrowser, because I explicitly *didn't* want testing to be part of the "contract" (think "API") for releases - I often depend on very specific pytest and -plugin versions, because I basically use qutebrowser as a test-bed for new pytest features and such.

I decided to give it a try anyways, and so far, things have been going surprisingly smooth, with AFAIK a couple of distributions running the tests in their packaging. So in general, especially if you expect your thing to be packaged, I'd say it's probably a good idea.

What I wouldn't do is *installing* the tests, because that kinda goes against the usual pattern of having `tests/` outside of your package directory (and you don't want to be installing a top-level `tests` package).

However, in this specific case, I explicitly *don't* want pytest-vw to be packaged in any distribution, because it's a joke package, and packaging it only seems to generate noise (and maintenance burden) for distributions. I'm not sure why it's even on PyPI at all. Let's not take the joke too far, especially for something nobody really would get any value from (quite the opposite...).

**Comment by jgarte** [comment]
> What I wouldn't do is installing the tests,

I agree and we never install the tests.

> I explicitly don't want pytest-vw to be packaged in any distribution,

Ok, I won't package it.

Thanks for more context and the info. It's much appreciated.

I wish you more merry pycoverage and a Happy New Year!
